nginx:
  image: nginx:alpine
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/nginx/conf.d:/etc/nginx/conf.d/:ro
    - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./log/nginx/:/var/log/nginx/:rw
  links:
    - php56:fpm

php56:
  build: ./dockerfiles/php/php56/
  expose:
    - "9000"
  volumes:
    - ./www/:/var/www/html/:rw
    - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
    - ./conf/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:rw
    - ./log/php-fpm/:/var/log/php-fpm/:rw
  links:
    - mysql:mysql
    - redis:redis

mysql:
  build: ./dockerfiles/mysql
  ports:
    - "3306:3306"
  volumes:
    - ./conf/mysql/my.cnf:/etc/mysql/my.cnf:ro
    - ./data/mysql/:/var/lib/mysql/:rw
    - ./log/mysql/:/var/log/mysql/:rw
    - ./conf/mysql/init:/tmp/init:ro
  environment:
    MYSQL_ROOT_PASSWORD_FILE: /tmp/init/root_password.conf

redis:
  image: redis:alpine
  ports:
    - "6379:6379"
  volumes:
    - ./conf/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro
    - ./data/redis/:/data:rw
    - ./log/redis/:/log/redis:rw
  command: /bin/sh -c "touch /log/redis/redis.log && redis-server /usr/local/etc/redis/redis.conf"